In [2]:
import pandas as pd

import unicodedata
import re
def clean_text(s):
    # bỏ dấu tiếng Việt
    s = unicodedata.normalize('NFD', s)
    s = ''.join(c for c in s if unicodedata.category(c) != 'Mn')
    
    # giữ lại chữ cái
    s = re.sub(r'[^a-zA-Z]', '', s)
    
    return s.lower()

s = "Tổng sản phẩm trong nước (GDP)!!!"
print(clean_text(s))





file_path = '../../../Bronze_Excel_Financial_Report/2023/IS_Thang/02-So-lieu-02-2023-1.xlsx'

excel_file = pd.ExcelFile(file_path)

all_sheets = excel_file.sheet_names

import_index = -1
export_index = -1

for i in range(len(all_sheets)):
    name = clean_text(all_sheets[i])
    if any(sheet in name for sheet in ['nk', 'nhapkhau']) and 'quy' not in name and 'gia' not in name:
        import_index = i
    if any(sheet in name for sheet in ['xk', 'xuatkhau']) and 'quy' not in name and 'gia' not in name:
        export_index = i

import_sheet = pd.read_excel(file_path, sheet_name= all_sheets[import_index], header= None)
export_sheet = pd.read_excel(file_path, sheet_name= all_sheets[export_index], header= None)

tongsanphamtrongnuocgdp

In [ ]:
def extract_intenational_ecommerce_data_sheet(sheet : pd.DataFrame, type : str):
    # xóa các row không cần thiết
    num_of_remove_row = 0
    for i in range(len(sheet)):
        num_of_remove_row += 1
        if isinstance(sheet.iloc[i, 0], str) and 'mathangchuyeu' in clean_text(sheet.iloc[i, 0]): break

    if type == 'import':
        sheet = sheet.iloc[num_of_remove_row:len(sheet) - 1, ::].reset_index(drop =True)
        
    else: sheet = sheet.iloc[num_of_remove_row::, ::].reset_index(drop =True)

    name_colums = ['product_name', 'luong_thang_nay', 'gia tri thang nay']
    #xoa cac cot kh can thiet
    sheet = sheet.iloc[::, [1, 2, 3]]
    sheet.columns = name_colums

    if type == 'import': 
        for i in range(len(sheet)):
            if 'oto' == clean_text(sheet.loc[i, 'product_name']):
                sheet.loc[i, 'product_name'] = 'Ô tô và linh kiện'
            if 'Trong đó: Nguyên chiếc(*)' in sheet.loc[i, 'product_name'] :
                sheet.loc[ i, 'product_name'] = 'Ô tô nguyên chiếc' 
        
    return sheet

In [ ]:
import_sheet
df = extract_intenational_ecommerce_data_sheet(export_sheet, 'export')

In [5]:
df

                            product_name luong_thang_nay gia tri thang nay
0                              Thủy sản              NaN               550
1                                Rau quả             NaN               350
2                               Hạt điều              30        171.155962
3                                 Cà phê             180         392.70184
4                                    Chè               8         13.194224
5                               Hạt tiêu              28         85.641758
6                                    Gạo             430        230.589474
7                Sắn và sản phẩm của sắn             500        189.836918
8                     Clanhke và xi măng            3200        136.533789
9                              Dầu thô               280        203.456565
10                              Xăng dầu             130        102.907144
11                             Hóa chất              NaN               220
12                     Sản phẩm hóa chất             NaN               220
13                  Chất dẻo nguyên liệu             180        208.987866
14                  Sản phẩm từ chất dẻo             NaN               350
15                                Cao su             150        211.649897
16         Túi xách, ví, va li, mũ, ô dù             NaN               260
17                     Gỗ và sản phẩm gỗ             NaN               800
18          Giấy và các sản phẩm từ giấy             NaN               170
19                  Xơ, sợi dệt các loại              90        360.264725
20                              Dệt, may             NaN              2300
21                              Giày dép             NaN              1400
22    Nguyên phụ liệu dệt, may, da, giày             NaN               160
23                              Sắt thép             700        525.335678
24                  Sản phẩm từ sắt thép             NaN               350
25      Kim loại thường khác và sản phẩm             NaN               350
26        Điện tử, máy tính và linh kiện             NaN              3700
27               Điện thoại và linh kiện             NaN              4400
28          Máy ảnh, máy quay phim và LK             NaN               450
29     Máy móc thiết bị, dụng cụ PT khác             NaN              3500
30                  Dây điện và cáp điện             NaN               270
31       Phương tiện vận tải và phụ tùng             NaN              1100
32      SP nội thất từ chất liệu khác gỗ             NaN               180
33  Đồ chơi, dụng cụ thể thao và bộ phận             NaN               300

In [ ]:
df =extract_intenational_ecommerce_data_sheet(import_sheet, 'import')
df

                        product_name luong_thang_nay gia tri thang nay
0                           Thủy sản             NaN               250
1                Sữa và sản phẩm sữa             NaN                95
2                            Rau quả             NaN               140
3                           Hạt điều             150        211.315068
4                                Ngô             750        251.823589
5             Thức ăn gia súc và NPL             NaN               450
6           Quặng và khoáng sản khác            1500        172.919558
7                            Than đá            3700        613.490392
8                            Dầu thô             700        424.513229
9                           Xăng dầu             900        786.487875
10                  Khí đốt hóa lỏng             150        127.187292
11                         Hóa chất              NaN               550
12                 Sản phẩm hoá chất             NaN               600
13                          Tân dược             NaN               350
14                         Phân bón              120         39.471475
15                         Chất dẻo              550        775.560919
16                 Sản phẩm chất dẻo             NaN               500
17                            Cao su             130         178.53081
18                 Gỗ và sản phẩm gỗ             NaN               150
19                     Giấy các loại             190        172.201445
20                             Bông               72        166.426218
21                          Sợi dệt               75        147.225578
22                               Vải             NaN               700
23      Nguyên PL dệt, may, giày dép             NaN               380
24  Thủy tinh và các SP từ thủy tinh             NaN               130
25                 Phế liệu sắt thép             550         227.72856
26                         Sắt thép              700        582.669573
27              Sản phẩm từ sắt thép             NaN               350
28              Kim loại thường khác             150         682.75008
29        SP từ kim loại thường khác             NaN               180
30           Điện tử, máy tính và LK             NaN              6200
31          Hàng điện gia dụng và LK             NaN               180
32           Điện thoại và linh kiện             NaN               600
33      Máy ảnh, máy quay phim và LK             NaN               190
34      Máy móc thiết bị, DC PT khác             NaN              2800
35              Dây điện và cáp điện             NaN        166.397127
36                 Ô tô và linh kiện             NaN        615.897464
37                 Ô tô nguyên chiếc           30000         297.86866