In [ ]:
import pandas as pd 

file_path ='../../../Bronze_Excel_Financial_Report/2016/Is_Quy/Bieu-6.2016.xlsx'
excel_file = pd.ExcelFile(file_path)
all_sheet = excel_file.sheet_names
all_sheet

['GDP',
 'GTSX',
 'dx (2)',
 'dxdp (2)',
 'thuy san',
 'IIP',
 'SP',
 'CS TT TK',
 'LAO DONG',
 'VĐTTXH',
 'VonDT',
 'FDI',
 'Tongmuc',
 'XK',
 'NK',
 'CPI',
 'CSG_NLTS',
 'CSG_CN',
 'CSG_dau vao',
 'csg XK ',
 'csg NK ',
 'TygiaTM',
 'CSG_cuoc van tai',
 'CSGDichvu',
 'Vantai',
 'Du lich']

In [52]:
import unicodedata
import re
def clean_text(s):
    # bỏ dấu tiếng Việt
    s = unicodedata.normalize('NFD', s)
    s = ''.join(c for c in s if unicodedata.category(c) != 'Mn')
    
    # giữ lại chữ cái
    s = re.sub(r'[^a-zA-Z]', '', s)
    
    return s.lower()

s = "Tổng sản phẩm trong nước (GDP)!!!"
print(clean_text(s))

tongsanphamtrongnuocgdp

In [53]:
#  Kiểm tra có công bố VDTTXH không
vdttxh_sheet_index = -1
for i in range(len(all_sheet)):
    sheet_name = all_sheet[i]
    cleaned_sheet_name = clean_text(sheet_name)
    if 'ttxh' in cleaned_sheet_name:
        vdttxh_sheet_index = i
        break

if(vdttxh_sheet_index == -1):
    print("Khong cong bo vddtxh")
else:
    print(vdttxh_sheet_index)

9

In [54]:
vdt_sheet = pd.read_excel(file_path, sheet_name=all_sheet[vdttxh_sheet_index], header= None)

In [55]:
column_names = ['investment_type', 'thuc_hien_quy_truoc', 'uoc_tinh_quy_nay']
vdt_sheet = vdt_sheet.iloc[::, 1:4]
vdt_sheet.columns = column_names

In [56]:
num_of_removed_row = -1
col = vdt_sheet['uoc_tinh_quy_nay']
for i in range(len(col)):
    num_of_removed_row += 1
    if type(col[i]) is str:
        break

vdt_sheet = vdt_sheet.iloc[num_of_removed_row::, ::].reset_index(drop= True)

In [57]:
vdt_sheet

,investment_type,thuc_hien_quy_truoc,uoc_tinh_quy_nay
0,NaN,Thực hiện,Ước tính
1,NaN,quý I,quý II
2,NaN,năm 2016,năm 2016
3,NaN,NaN,NaN
4,NaN,NaN,NaN
5,NaN,276.5,341.7
6,Vốn đầu tư thuộc ngân sách Nhà nước,42.8,64.2
7,Vốn trái phiếu Chính phủ,8.8,11.8
8,Vốn tín dụng đầu tư theo kế hoạch NN,12.1,14.9
9,Vốn vay từ các nguồn khác \n(của khu vực Nhà n...,17.2,19.6
10,Vốn đầu tư của doanh nghiệp Nhà nước\n(Vốn tự có),13.1,16.4
11,Vốn đầu tư của dân cư và tư nhân,102.5,128.2
12,Vốn đầu tư trực tiếp nước ngoài,76.5,81.7
13,Vốn huy động khác,3.5,4.9

In [58]:
if 'quy' in clean_text(vdt_sheet['thuc_hien_quy_truoc'][1]):
    print('a')
else: print('b')

num_of_removed_row = -1
for i in range(len(vdt_sheet['investment_type'])):
    num_of_removed_row += 1
    if type(vdt_sheet['investment_type'][i]) is str:
        break

num_of_removed_row

vdt_sheet = vdt_sheet.iloc[num_of_removed_row::, ::].reset_index(drop= True)

a

In [59]:
vdt_sheet

,investment_type,thuc_hien_quy_truoc,uoc_tinh_quy_nay
0,Vốn đầu tư thuộc ngân sách Nhà nước,42.8,64.2
1,Vốn trái phiếu Chính phủ,8.8,11.8
2,Vốn tín dụng đầu tư theo kế hoạch NN,12.1,14.9
3,Vốn vay từ các nguồn khác \n(của khu vực Nhà n...,17.2,19.6
4,Vốn đầu tư của doanh nghiệp Nhà nước\n(Vốn tự có),13.1,16.4
5,Vốn đầu tư của dân cư và tư nhân,102.5,128.2
6,Vốn đầu tư trực tiếp nước ngoài,76.5,81.7
7,Vốn huy động khác,3.5,4.9